hw01: add
pinigor1974/2024-11-otus-spring-Polukhin pull request #1
Opened 2024-12-08 13:56 UTC by pinigor1974

2024-12-09 18:26 UTC, VladimirMagerov requested changes

2024-12-09 18:26 UTC, VladimirMagerov commented on hw01/src/main/java/ru/otus/hw/service/StreamsIOService.java
> +public class StreamsIOService implements IOService {
Для однообразия предлагаю использовать `@RequiredArgsConstructor`, как и в других сервисах

2024-12-09 18:26 UTC, VladimirMagerov commented on hw01/src/main/java/ru/otus/hw/service/TestServiceImpl.java
> +        questionDao.findAll().forEach(q -> ioService.printLine(q.toString()));
Предлагаю вывести вопросы и ответы в отформатированном удобочитаемом виде, а не просто сплошной строкой

2024-12-09 19:16 UTC, pinigor1974 commented on hw01/src/main/java/ru/otus/hw/service/StreamsIOService.java
> +public class StreamsIOService implements IOService {
fixed

2024-12-09 19:16 UTC, pinigor1974 commented on hw01/src/main/java/ru/otus/hw/service/TestServiceImpl.java
> +        questionDao.findAll().forEach(q -> ioService.printLine(q.toString()));
fixed

2024-12-10 15:14 UTC, VladimirMagerov approved these changes

2024-12-10 16:56 UTC, merged