add
pinigor1974/2024-11-otus-spring-Polukhin pull request #4
Opened 2024-12-22 09:58 UTC by pinigor1974

2024-12-25 13:26 UTC, VladimirMagerov requested changes

2024-12-25 13:26 UTC, VladimirMagerov commented on hw03/src/main/java/ru/otus/hw/Application.java
> +    public static void main(String[] args) {
Что-то не так с выводом результатов теста:
![image](https://github.com/user-attachments/assets/958057c8-edc8-4dfc-bb71-3171d9bd7ae9)

2024-12-25 13:26 UTC, VladimirMagerov commented on hw03/src/main/java/ru/otus/hw/service/TestServiceImpl.java
> +public class TestServiceImpl implements TestService {
Отсутствуют тесты, предлагаю всё-таки потренироваться в их написании с учётом комментариев к предыдущему ДЗ.

2025-01-14 16:43 UTC, VladimirMagerov requested changes

2025-01-14 16:43 UTC, VladimirMagerov commented on hw03/.gitignore
> +target/
Ошибка во время вывода результатов теста - вероятно, что-то напутано с кодом выводимого сообщения:
![image](https://github.com/user-attachments/assets/549bf37c-4f9c-4480-89a1-6e769bac9875)

2025-01-14 16:43 UTC, VladimirMagerov commented on hw03/src/test/java/ru.otus.test.hw/QuestionDaoTest.java
> +    void testQuestionDao(){
Конфигурационный файл и файл с вопросами для тестов должны быть свои (отдельные). Сейчас используется файл и настройки из основной программы, и если там будут изменения - упадут и тесты, а этого быть не должно.

2025-01-14 16:43 UTC, VladimirMagerov commented on hw03/src/test/java/ru.otus.test.hw/QuestionDaoTest.java
> +    void testQuestionDao(){
В дополнение к этому, рекомендую проверять не только количество считанных вопросов, но и их содержимое - так тест будет надёжнее.

2025-01-14 16:43 UTC, VladimirMagerov commented on hw03/src/test/java/ru.otus.test.hw/ApplicationTest.java
> +    void shouldCheckTestServiceImpl() {
В целом, для обычного юнит-теста поднимать целый тестовый контекст совсем не обязательно, предлагаю обойтись обычными моками (не бинами) - пример можно глянуть тут: https://www.baeldung.com/mockito-annotations

2025-02-04 14:28 UTC, pinigor1974 commented on hw03/.gitignore
> +target/
fixed

2025-02-04 14:28 UTC, pinigor1974 commented on hw03/src/main/java/ru/otus/hw/service/TestServiceImpl.java
> +public class TestServiceImpl implements TestService {
fixed

2025-02-04 16:12 UTC, pinigor1974 commented on hw03/src/test/java/ru.otus.test.hw/QuestionDaoTest.java
> +    void testQuestionDao(){
fixed

2025-02-05 10:22 UTC, pinigor1974 commented on hw03/src/test/java/ru.otus.test.hw/QuestionDaoTest.java
> +    void testQuestionDao(){
fixed

2025-02-05 10:22 UTC, pinigor1974 commented on hw03/.gitignore
> +target/
fixed

2025-02-05 10:22 UTC, pinigor1974 commented on hw03/src/main/java/ru/otus/hw/service/TestServiceImpl.java
> +public class TestServiceImpl implements TestService {
fixed

2025-02-05 10:23 UTC, pinigor1974 commented on hw03/src/main/java/ru/otus/hw/Application.java
> +    public static void main(String[] args) {
fixed

2025-02-06 10:07 UTC, pinigor1974 commented on hw03/src/test/java/ru.otus.test.hw/ApplicationTest.java
> +    void shouldCheckTestServiceImpl() {
fixed

2025-02-07 15:58 UTC, VladimirMagerov commented on hw03/.gitignore
> +target/
Ошибка всё ещё не исправлена

2025-02-07 16:02 UTC, VladimirMagerov approved these changes

2025-02-07 16:02 UTC, VladimirMagerov commented on hw03/src/test/java/ru.otus.test.hw/ApplicationTest.java
> +        testService = new TestServiceImpl(ioService, csvQuestionDao);
Используя `@InjectMocks` над объявлением `testService`, мы можем избавиться от этого инит метода.

2025-02-07 16:02 UTC, VladimirMagerov commented on hw03/src/test/java/ru.otus.test.hw/QuestionDaoTest.java
> +    void testQuestionDao(){
Опять же, можно ещё проверить и текст ответов, и какой из них правильный для каждого загруженного вопроса - будет надежнее.

2025-02-08 18:00 UTC, merged